name: Release

on:
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.get_date.outputs.DATE }}
    steps:
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
